[package]
name = "testing-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.210"
serde_json = "1.0.128"
tokio = "1.36.0"
frcrs = { git = "https://github.com/Team-2502/frcrs.git" }
