// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOUR DOING

use tokio::{runtime::Runtime, task::LocalSet};
use frcrs::{init_hal, hal_report, observe_user_program_starting};
use robotcode::configure;

fn main() {
    let executor = Runtime::new().unwrap();
    let local = LocalSet::new();

    let controller = local.run_until(async {
        if !init_hal() {
            panic!("Failed to initialize HAL");
        }

        hal_report(2, 7, 0, "2024.2.1".to_string());

        observe_user_program_starting();

        configure().await;
    });

    executor.block_on(controller);
}
